name: RedditApp
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  nb_utils: ^4.6.7
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  http: ^0.13.0
  stream_transform: ^2.0.0

dev_dependencies:

flutter:
  uses-material-design: true
